language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-23.0.2
    - android-23

script: "./gradlew build --stacktrace"  
